### ISSUE TITLE
Not able to find the path for matlab

### ISSUE THREAD

**Issue by divyoj** [muschellij2/matlabr#2]
Hi, i am trying to call a matlab script using R, and for the same I used matlabr. 
The code is working fine on Windws, however on Ubuntu 18, it is getting stuck.
Following is the error message:
'''
Error in get_matlab(desktop = desktop, splash = splash, display = display,  : 
  !is.null(mpath) is not TRUE
Calls: getEMTCor ... mlrEMTPred -> run_matlab_script -> get_matlab -> stopifnot
'''
 I have MATLAB 2019 installed in "/usr/local". 
R version 4.0.0

I think the issue is that get_matlab doesnt search in /usr/local/".
Please tell me what should I do.

**Comment by muschellij2** [comment]
You should be able to do:
```r
options("matlab.path" = "/usr/local/")
```
Are you saying the path to matlab is in`/usr/local/matlab`?  I'd imagine it'd be `/usr/local/bin/matlab` at the least.  `matlabr` searches `/usr/local/bin` and `/usr/bin`.
