### ISSUE TITLE
Suppressing MATLAB console output when establishing a connection.

### ISSUE THREAD

**Issue by calenwalshe** [muschellij2/matlabr#3]
When I open up MATLAB to run commands I get the standard MATLAB console output output on the R command line. Providing the nosplash flag doesn't suppress this.

I've tried standard tricks like piping all output to the nul, but these don't seem to do the trick either. 

Is there a way to suppress ALL output from the MATLAB console. Additionally, suppress the opening dialogue, but allow any display commands within MATLAB to be passed through. In other words, open completely silently but display all other MATLAB output.

I'm using MATLAB R to run many jobs in parallel so the opening text is a bit annoying.

Thanks!

**Comment by muschellij2** [comment]
Short answer - no.

**Comment by muschellij2** [comment]
https://www.mathworks.com/matlabcentral/answers/24677-is-there-a-way-to-suppress-the-startup-help-message-when-running-matlab-from-the-command-line
